# Generated by Django 3.1.3 on 2021-08-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_laws_data',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
