# Generated by Django 3.1.3 on 2021-08-17 12:26

from django.db import migrations, models
import pybo.models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='model_laws_data',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AlterField(
            model_name='model_laws_data',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=pybo.models.get_file_path, verbose_name='파일'),
        ),
    ]
