# Generated by Django 3.1.3 on 2021-08-24 12:37

from django.db import migrations, models
import django.db.models.deletion
import pybo.models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_auto_20210817_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_laws_data',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to=pybo.models.get_file_path, verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='model_laws_data',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=pybo.models.get_file_path, verbose_name='이미지'),
        ),
        migrations.CreateModel(
            name='laws_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('laws_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.model_laws_data')),
            ],
        ),
    ]
