# Generated by Django 3.1.3 on 2021-09-26 11:26

from django.db import migrations, models
import django.db.models.deletion
import pybo.models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_auto_20210824_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='guide_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.question')),
            ],
        ),
        migrations.CreateModel(
            name='Model_guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('upload_files', models.FileField(blank=True, null=True, upload_to=pybo.models.get_file_path, verbose_name='파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to=pybo.models.get_file_path, verbose_name='이미지')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Model_regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('upload_files', models.FileField(blank=True, null=True, upload_to=pybo.models.get_file_path, verbose_name='파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to=pybo.models.get_file_path, verbose_name='이미지')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='regulation_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.question')),
            ],
        ),
        migrations.CreateModel(
            name='SKTL_policy_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.question')),
            ],
        ),
        migrations.CreateModel(
            name='trend_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Model_GuideManual',
        ),
        migrations.DeleteModel(
            name='Model_regulation_data',
        ),
        migrations.AddField(
            model_name='model_sktl_policy',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AddField(
            model_name='model_sktl_policy',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=pybo.models.get_file_path, verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='model_sktl_policy',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to=pybo.models.get_file_path, verbose_name='파일'),
        ),
        migrations.AddField(
            model_name='model_trend',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AddField(
            model_name='model_trend',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=pybo.models.get_file_path, verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='model_trend',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to=pybo.models.get_file_path, verbose_name='파일'),
        ),
    ]
